<h1 class="m-t-0">Pridať nový záznam</h1>

<form method="post" action="/dns/store">
    <div>
        <label for="type">Type:</label>
        <select name="type" id="type" class="form jsSelect">
            <?php foreach ($types as $key => $type) : ?>
                <option value="<?= $key ?>"><?= $type ?></option>
            <?php endforeach ?>
        </select>
    </div>

    <div class="jsInput">
        <label for="name">Name</label>
        <!--<input id="name" type="text" value="<?/*= $dns['name'] */?>" required name="name" pattern="[a-z]{0,1}\w+\W*" class="form jsRequired">-->
        <input id="name" type="text" name="name"class="form">
    </div>

    <div class="jsInput">
        <label for="content">Content</label>
        <input id="content" type="text" required value="<?= $dns['content'] ?>"  pattern="(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)_*(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)_*){3}" name="content" class="form jsRequired">
    </div>

    <div class="jsInput d-none">
        <label for="prio">Prio</label>
        <input id="prio" type="number" name="prio" value="<?= $dns['prio'] ?>" class="form jsRequired">
    </div>

    <div class="jsInput d-none">
        <label for="port">Port</label>
        <input id="port" type="number" name="port"  value="<?= $dns['port'] ?>" class="form jsRequired">
    </div>

    <div class="jsInput d-none">
        <label for="weight">Weight</label>
        <input id="weight" type="number" name="weight" value="<?= $dns['weight'] ?>" class="form jsRequired">
    </div>

    <div class="jsInput">
        <label for="ttl">Ttl</label>
        <input id="ttl" type="number" name="ttl" class="form" value="600">
    </div>

    <div class=right>
        <a href="/home" class="m-r-10">Zrušiť</a>
        <button type="submit" class="btn btn-yellow">Uložiť</button>
    </div>
</form>